# Common properties (applies to all profiles)
spring:
  application:
    name: gcide-xml-parser
  profiles:
    active: sqlite  # Default profile

---
# H2 profile-specific properties
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:file:./cidedb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      data-locations:
      - schema-h2.sql

---
# SQLite profile-specific properties
spring:
  config:
    activate:
      on-profile: sqlite
  datasource:
    url: jdbc:sqlite:database.sqlite
    driverClassName: org.sqlite.JDBC
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      data-locations:
      - schema-sqlite.sql