-----------------------------
-- Cleanup: Drop existing tables
-----------------------------
DROP TABLE IF EXISTS definition CASCADE;
DROP TABLE IF EXISTS synonyms CASCADE;
DROP TABLE IF EXISTS dictionary_entry CASCADE;
DROP TABLE IF EXISTS dictionary_entry_parts_of_speech CASCADE;
DROP TABLE IF EXISTS quote CASCADE;
DROP TABLE IF EXISTS verb_morphology_entry CASCADE;
DROP TABLE IF EXISTS verb_morphology_entry_parts_of_speech CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-----------------------------
-- Table Definitions
-----------------------------
CREATE TABLE dictionary_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entry_word VARCHAR(255),
    head_word VARCHAR(255),
    source VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE synonyms (
    dictionary_entry_id INTEGER,
    synonym TEXT,
    FOREIGN KEY (dictionary_entry_id) REFERENCES dictionary_entry(id)
);


CREATE TABLE dictionary_entry_parts_of_speech (
    dictionary_entry_id BIGINT,
    parts_of_speech VARCHAR(255)
);

CREATE TABLE definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    dictionary_entry_id BIGINT,
    mark VARCHAR(255),
    source VARCHAR(255),
    definition TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE quote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    dictionary_entry_id BIGINT,
    author VARCHAR(1000),
    source VARCHAR(255),
    text TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE verb_morphology_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    dictionary_entry_id BIGINT,
    conjugated_form VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE verb_morphology_entry_parts_of_speech (
    verb_morphology_entry_id BIGINT,
    parts_of_speech VARCHAR(255)
);


CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);


-----------------------------
-- Foreign Key Constraints
-----------------------------
ALTER TABLE definition
    ADD CONSTRAINT fk_definition_dictionary_entry
    FOREIGN KEY (dictionary_entry_id)
    REFERENCES dictionary_entry;

ALTER TABLE dictionary_entry_parts_of_speech
    ADD CONSTRAINT fk_dictionary_entry_parts_of_speech
    FOREIGN KEY (dictionary_entry_id)
    REFERENCES dictionary_entry;

ALTER TABLE quote
    ADD CONSTRAINT fk_quote_dictionary_entry
    FOREIGN KEY (dictionary_entry_id)
    REFERENCES dictionary_entry;

ALTER TABLE verb_morphology_entry
    ADD CONSTRAINT fk_verb_morphology_entry
    FOREIGN KEY (dictionary_entry_id)
    REFERENCES dictionary_entry;

ALTER TABLE verb_morphology_entry_parts_of_speech
    ADD CONSTRAINT fk_verb_morph_parts_of_speech
    FOREIGN KEY (verb_morphology_entry_id)
    REFERENCES verb_morphology_entry;



-----------------------------
-- Initial Data
-----------------------------

INSERT INTO users (username, password) VALUES ('admin', 'admin@123');
INSERT INTO users (username, password) VALUES ('user', 'user@123');
