/*
 * Copyright (C) 2025 Suvankar Mitra
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package com.moo.suvankar.gxp.constants;

import java.util.HashMap;
import java.util.Map;

public class Abbreviations {
    public static final Map<String, String> ABBREVIATION_MAP = new HashMap<>();

    static {
        ABBREVIATION_MAP.put("a.","adjective");
        ABBREVIATION_MAP.put("adj.","adjective");
        ABBREVIATION_MAP.put("abbrev.","abbreviated");
        ABBREVIATION_MAP.put("abl.","ablative");
        ABBREVIATION_MAP.put("Abp.","Archbishop");
        ABBREVIATION_MAP.put("acc.","accusative");
        ABBREVIATION_MAP.put("Acous.","Acoustics");
        ABBREVIATION_MAP.put("act.","active");
        ABBREVIATION_MAP.put("adv.","adverb");
        ABBREVIATION_MAP.put("Agric.","Agriculture");
        ABBREVIATION_MAP.put("Alban.","Albanian");
        ABBREVIATION_MAP.put("Alg.","Algebra");
        ABBREVIATION_MAP.put("Am., Amer.","America, American");
        ABBREVIATION_MAP.put("Am.","Amos");
        ABBREVIATION_MAP.put("Am. Cyc.","Appleton's American Cyclopedia");
        ABBREVIATION_MAP.put("Anal. Geom.","Analytical Geometry");
        ABBREVIATION_MAP.put("Anat.","Anatomy");
        ABBREVIATION_MAP.put("Anc.","Ancient, anciently");
        ABBREVIATION_MAP.put("Angl. Ch.","Anglican Church");
        ABBREVIATION_MAP.put("Antiq.","Aniquities");
        ABBREVIATION_MAP.put("aor.","aorist");
        ABBREVIATION_MAP.put("Ar.","Arabic");
        ABBREVIATION_MAP.put("Arch.","Architecture");
        ABBREVIATION_MAP.put("Arch. Pub. Soc.","Architectural Pub. Society");
        ABBREVIATION_MAP.put("Arith.","Arithmetic");
        ABBREVIATION_MAP.put("Arm.","Armorican");
        ABBREVIATION_MAP.put("Armor.","Armorican");
        ABBREVIATION_MAP.put("AS.","Anglo-Saxon");
        ABBREVIATION_MAP.put("Astrol.","Astrology");
        ABBREVIATION_MAP.put("Astron.","Astronomy");
        ABBREVIATION_MAP.put("aug.","augmentative");
        ABBREVIATION_MAP.put("Bank.","Banking");
        ABBREVIATION_MAP.put("Beau. & Fl. |","Beaumont & Fletcher");
        ABBREVIATION_MAP.put("B. & Fl.    |","Beaumont & Fletcher");
        ABBREVIATION_MAP.put("Bib.","Biblical");
        ABBREVIATION_MAP.put("Bib. Sacra","Bibliotheca Sacra");
        ABBREVIATION_MAP.put("Bibliog.","Bibliography");
        ABBREVIATION_MAP.put("Biol.","Biology");
        ABBREVIATION_MAP.put("Bisc.","Biscayan");
        ABBREVIATION_MAP.put("B. Jon.","Ben Jonson");
        ABBREVIATION_MAP.put("Bk. of Com. Prayer","Book of Common Prayer");
        ABBREVIATION_MAP.put("Blackw. Mag.","Blackwood's Magazine");
        ABBREVIATION_MAP.put("Bohem.","Bohemian");
        ABBREVIATION_MAP.put("Bot.","Botany, botanical");
        ABBREVIATION_MAP.put("Bp.","Bishop");
        ABBREVIATION_MAP.put("Brande & C.","Brande & Cox");
        ABBREVIATION_MAP.put("Braz.","Brazilian");
        ABBREVIATION_MAP.put("Brit. Critic","British Critic");
        ABBREVIATION_MAP.put("Brit. Quar. Rev.","British Quarterly Review");
        ABBREVIATION_MAP.put("Burl.","Burlesque");
        ABBREVIATION_MAP.put("C.","Centigrade");
        ABBREVIATION_MAP.put("Cant.","Canticles (Song of Solomon)");
        ABBREVIATION_MAP.put("Carp.","Carpentry");
        ABBREVIATION_MAP.put("Catal.","Catalan");
        ABBREVIATION_MAP.put("Cath. Dict.","Catholic Dictionary");
        ABBREVIATION_MAP.put("Celt.","Celtic");
        ABBREVIATION_MAP.put("Cf.","Confer (compare)");
        ABBREVIATION_MAP.put("Ch.","Church");
        ABBREVIATION_MAP.put("Chald.","Chaldee");
        ABBREVIATION_MAP.put("Chem.","Chemistry");
        ABBREVIATION_MAP.put("Ch. Hist.","Church History");
        ABBREVIATION_MAP.put("Chin.","Chinese");
        ABBREVIATION_MAP.put("Chron.","Chronology, Chronicles");
        ABBREVIATION_MAP.put("Civ.","Civil");
        ABBREVIATION_MAP.put("Class.","Classical");
        ABBREVIATION_MAP.put("Class. Myth.","Classical Mythology");
        ABBREVIATION_MAP.put("Col.","Colossians");
        ABBREVIATION_MAP.put("Colloq., coll.","Colloquial, colloquially");
        ABBREVIATION_MAP.put("Com.","Commerce, Common");
        ABBREVIATION_MAP.put("comp.","compound, compounded, composition");
        ABBREVIATION_MAP.put("compar.","comparative");
        ABBREVIATION_MAP.put("conj.","conjunction");
        ABBREVIATION_MAP.put("Con. Sect.","Conic Sections");
        ABBREVIATION_MAP.put("contr.","contracted, contraction");
        ABBREVIATION_MAP.put("Copt.","Coptic");
        ABBREVIATION_MAP.put("Corn.","Cornish");
        ABBREVIATION_MAP.put("corrupt.","corrupted, corruption");
        ABBREVIATION_MAP.put("Cotgr.","Cotgrave");
        ABBREVIATION_MAP.put("Cyc. Med.","Cyclopedia of Practical Medicine");
        ABBREVIATION_MAP.put("Crim. Law","Criminal Law");
        ABBREVIATION_MAP.put("Crystallog.","Crystallography");
        ABBREVIATION_MAP.put("Cyc.","Cyclopedia");
        ABBREVIATION_MAP.put("D.","Dutch");
        ABBREVIATION_MAP.put("Dan.","Danish, Daniel");
        ABBREVIATION_MAP.put("dat.","dative");
        ABBREVIATION_MAP.put("def.","definitions");
        ABBREVIATION_MAP.put("Deut.","Deuteronomy");
        ABBREVIATION_MAP.put("Dial.","Dialectic");
        ABBREVIATION_MAP.put("dim.","diminutive");
        ABBREVIATION_MAP.put("Diosc.","dioscorides");
        ABBREVIATION_MAP.put("Disp.","Dispensatory");
        ABBREVIATION_MAP.put("Disus.","Disused");
        ABBREVIATION_MAP.put("Dom. Econ.","Domestic Economy");
        ABBREVIATION_MAP.put("Dublin Univ. Mag.","Dublin University Magazine");
        ABBREVIATION_MAP.put("Dyn.","Dynamics");
        ABBREVIATION_MAP.put("E.","English");
        ABBREVIATION_MAP.put("Eccl.","Ecclesiastical, Ecclesiastes");
        ABBREVIATION_MAP.put("Eccl. Hist.","Ecclesiastical History");
        ABBREVIATION_MAP.put("Ecclus.","Ecclesiasticus");
        ABBREVIATION_MAP.put("Eclec. Rev.","Eclectic Review");
        ABBREVIATION_MAP.put("Ed. Rev.","Edinburgh Review");
        ABBREVIATION_MAP.put("e. g.","<it>exemplia gratia</it> (for example)");
        ABBREVIATION_MAP.put("Egypt.","Egyptian");
        ABBREVIATION_MAP.put("Elect.","Electricity, Electrical");
        ABBREVIATION_MAP.put("emph.","emphatic");
        ABBREVIATION_MAP.put("Encyc.","Encyclopedia");
        ABBREVIATION_MAP.put("Encyc. Amer.","Encyclopedia Americana");
        ABBREVIATION_MAP.put("Encyc. Crit.","Encyclopedia Britannica");
        ABBREVIATION_MAP.put("Encyc. Dict.","Hunter's Encyclopedic Dictionary");
        ABBREVIATION_MAP.put("Eng.","England, English, Engraving");
//        ABBREVIATION_MAP.put("Eng.","Engraving");
        ABBREVIATION_MAP.put("Eng. Cyc.","English Cyclopedia");
        ABBREVIATION_MAP.put("Engin.","Engineering");
        ABBREVIATION_MAP.put("Eol.","Eolic");
        ABBREVIATION_MAP.put("Eph.","Ephesians");
        ABBREVIATION_MAP.put("Ephes.","Ephesians");
        ABBREVIATION_MAP.put("equiv.","equivalent");
        ABBREVIATION_MAP.put("Esd.","Esdras");
        ABBREVIATION_MAP.put("esp.","especially");
        ABBREVIATION_MAP.put("Etch. & Eng.","Etching & Engraving");
        ABBREVIATION_MAP.put("Ethnol.","Ethnology");
        ABBREVIATION_MAP.put("etym.","etymology");
        ABBREVIATION_MAP.put("etymol.","etymology");
        ABBREVIATION_MAP.put("Ex.","Exodus");
        ABBREVIATION_MAP.put("Exod.","Exodus");
        ABBREVIATION_MAP.put("Ezek.","Ezekiel");
        ABBREVIATION_MAP.put("F.","French");
        ABBREVIATION_MAP.put("f.","feminine");
        ABBREVIATION_MAP.put("fem.","feminine");
        ABBREVIATION_MAP.put("Fahr.","Fahrenheit");
        ABBREVIATION_MAP.put("Far.","Farriery");
        ABBREVIATION_MAP.put("Feud.","Feudal");
        ABBREVIATION_MAP.put("Fig.","Figurative, figuratively");
        ABBREVIATION_MAP.put("Fin.","Finnish");
        ABBREVIATION_MAP.put("For. Quart. Rev.","Foreign Quarterly Review");
        ABBREVIATION_MAP.put("Fort.","Fortification");
        ABBREVIATION_MAP.put("fr.","from");
        ABBREVIATION_MAP.put("Fr.","French");
        ABBREVIATION_MAP.put("freq.","frequentative");
        ABBREVIATION_MAP.put("Fries.","Friesic");
        ABBREVIATION_MAP.put("fut.","future");
        ABBREVIATION_MAP.put("G.","German");
        ABBREVIATION_MAP.put("Gael.","Gaelic");
        ABBREVIATION_MAP.put("Gal.","Galen, Galatians");
//        ABBREVIATION_MAP.put("Gal.","Galatians");
        ABBREVIATION_MAP.put("Galv.","Galvanism");
        ABBREVIATION_MAP.put("gen.","generally, genitive");
        ABBREVIATION_MAP.put("Geneal.","Genealogy");
        ABBREVIATION_MAP.put("Gent. Mag.","Gentleman's Magazine");
        ABBREVIATION_MAP.put("Geog.","Geography");
        ABBREVIATION_MAP.put("Geol.","Geology");
        ABBREVIATION_MAP.put("Geom.","Geometry");
        ABBREVIATION_MAP.put("Ger.","German");
        ABBREVIATION_MAP.put("Goth.","Gothic");
        ABBREVIATION_MAP.put("Gov. of Tongue","Government of the Tongue");
        ABBREVIATION_MAP.put("Gr.","Greek");
        ABBREVIATION_MAP.put("Gram.","Grammar");
        ABBREVIATION_MAP.put("Gris.","Grisons");
        ABBREVIATION_MAP.put("Gun.","Gunnery");
        ABBREVIATION_MAP.put("H.","High");
        ABBREVIATION_MAP.put("Hab.","Habakkuk");
        ABBREVIATION_MAP.put("Hag.","Haggai");
        ABBREVIATION_MAP.put("Ham. Nav. Encyc.","Hamersly's Naval Encyclopedia");
        ABBREVIATION_MAP.put("Heb.","Hebrew, Hebrews");
        ABBREVIATION_MAP.put("Her.","Heraldry");
        ABBREVIATION_MAP.put("Hind.","Hindostanee");
        ABBREVIATION_MAP.put("Hipp.","Hippocrates");
        ABBREVIATION_MAP.put("Hist.","History");
        ABBREVIATION_MAP.put("Horol.","Horology");
        ABBREVIATION_MAP.put("Hort.","Horticulture");
        ABBREVIATION_MAP.put("Hung.","Hungarian");
        ABBREVIATION_MAP.put("Hydraul.","Hydraulics");
        ABBREVIATION_MAP.put("Hydros.","Hydrostatics");
        ABBREVIATION_MAP.put("hypoth.","hypothetical");
        ABBREVIATION_MAP.put("Icel.","Icelandic");
        ABBREVIATION_MAP.put("i. e.","<it>id est</it> (that is)");
        ABBREVIATION_MAP.put("Illust.","Illustration, Illustrated");
        ABBREVIATION_MAP.put("imp.","imperfect");
        ABBREVIATION_MAP.put("Imp. Dict.","Imperial Dictionary");
        ABBREVIATION_MAP.put("incho.","inchoative");
        ABBREVIATION_MAP.put("ind.","indicative");
        ABBREVIATION_MAP.put("indef.","indefinite");
        ABBREVIATION_MAP.put("inf.","infinitive");
        ABBREVIATION_MAP.put("intens.","intensive");
        ABBREVIATION_MAP.put("interj.","interjection");
        ABBREVIATION_MAP.put("Internat. Cyc.","International Cyclopeia");
        ABBREVIATION_MAP.put("Ion.","Ionic");
        ABBREVIATION_MAP.put("i. q.","<it>idem quod</it> (the same as)");
        ABBREVIATION_MAP.put("Ir.","Irish");
        ABBREVIATION_MAP.put("Is.","Isaiah");
        ABBREVIATION_MAP.put("Isa.","Isaiah");
        ABBREVIATION_MAP.put("It.","Italian");
        ABBREVIATION_MAP.put("Jap.","Japanese");
        ABBREVIATION_MAP.put("Jas.","James");
        ABBREVIATION_MAP.put("Jav.","Javanese");
        ABBREVIATION_MAP.put("Jer.","Jeremiah");
        ABBREVIATION_MAP.put("Join.","Joinery");
        ABBREVIATION_MAP.put("Josh.","Joshua");
        ABBREVIATION_MAP.put("Judg.","Judges");
        ABBREVIATION_MAP.put("K.","Kings");
        ABBREVIATION_MAP.put("L.","Latin, Low");
//        ABBREVIATION_MAP.put("L.","Low");
        ABBREVIATION_MAP.put("Lam.","Lamentations");
        ABBREVIATION_MAP.put("Lapp.","Lappish");
        ABBREVIATION_MAP.put("Lat.","Latin");
        ABBREVIATION_MAP.put("LD.","Low Dutch");
        ABBREVIATION_MAP.put("Lett.","Lettish");
        ABBREVIATION_MAP.put("Lev.","Leviticus");
        ABBREVIATION_MAP.put("LG.","Low German");
        ABBREVIATION_MAP.put("LGr.","Low Greek");
        ABBREVIATION_MAP.put("Linn.","Linn<ae/us");
        ABBREVIATION_MAP.put("Lit., lit.","Literally, literally");
        ABBREVIATION_MAP.put("Lit.","Literature");
        ABBREVIATION_MAP.put("Lith.","Lithuanian");
        ABBREVIATION_MAP.put("LL.","Low Latin");
        ABBREVIATION_MAP.put("M.","Middle");
        ABBREVIATION_MAP.put("m.","masculine");
        ABBREVIATION_MAP.put("masc.","masculine");
        ABBREVIATION_MAP.put("Maced.","Macedonian");
        ABBREVIATION_MAP.put("Mach.","Machinery");
        ABBREVIATION_MAP.put("Mad.","Madam");
        ABBREVIATION_MAP.put("Mag.","Magazine");
        ABBREVIATION_MAP.put("Mal.","Malachi");
        ABBREVIATION_MAP.put("Malay.","Malayan");
        ABBREVIATION_MAP.put("Man.","Man<egrave/ge");
        ABBREVIATION_MAP.put("Manuf.","Manufacturing");
        ABBREVIATION_MAP.put("Mar.","Maritime");
        ABBREVIATION_MAP.put("Math.","Mathematics, Mathematical");
        ABBREVIATION_MAP.put("Matt.","Matthew");
        ABBREVIATION_MAP.put("Mech.","Mechanic");
        ABBREVIATION_MAP.put("Med.","Medicine");
        ABBREVIATION_MAP.put("Metal.","Metallurgy");
        ABBREVIATION_MAP.put("Metaph.","Metaphysics");
        ABBREVIATION_MAP.put("Meteor.","Meteorolgy");
        ABBREVIATION_MAP.put("mgr.","milligrams");
        ABBREVIATION_MAP.put("MHG.","Middle High German");
        ABBREVIATION_MAP.put("Micros.","Microscopy");
        ABBREVIATION_MAP.put("Mil.","Military");
        ABBREVIATION_MAP.put("Min.","Mineralogy");
        ABBREVIATION_MAP.put("Mir. for Mag.","Mirror for Magistrates");
        ABBREVIATION_MAP.put("MLG.","Middle Low German");
        ABBREVIATION_MAP.put("Moham.","Mohammedan");
        ABBREVIATION_MAP.put("Mozley & W.","Mozley & Whiteley");
        ABBREVIATION_MAP.put("Mus.","Music");
        ABBREVIATION_MAP.put("Myst.","Mysteries");
        ABBREVIATION_MAP.put("Myth.","Mythology");
        ABBREVIATION_MAP.put("N.","New");
        ABBREVIATION_MAP.put("n.","noun");
        ABBREVIATION_MAP.put("Nat. Hist.","Natural History");
        ABBREVIATION_MAP.put("Nat. ord.","Natural order");
        ABBREVIATION_MAP.put("Naut.","Nautical");
        ABBREVIATION_MAP.put("Nav.","Navy");
        ABBREVIATION_MAP.put("Navig.","Navigation");
        ABBREVIATION_MAP.put("N. Brit. Rev.","North British Review");
        ABBREVIATION_MAP.put("Neh.","Nehemiah");
        ABBREVIATION_MAP.put("neut.","neuter");
        ABBREVIATION_MAP.put("New Am. Cyc.","New American Cyclopedia");
        ABBREVIATION_MAP.put("New Month. Mag.","New Monthly Magazine");
        ABBREVIATION_MAP.put("NF.","New French");
        ABBREVIATION_MAP.put("NGr.","Mew Greek");
        ABBREVIATION_MAP.put("NHeb.","New Hebrew");
        ABBREVIATION_MAP.put("NL.","New Latin");
        ABBREVIATION_MAP.put("nom.","nominative");
        ABBREVIATION_MAP.put("Norm. F.","Norman French");
        ABBREVIATION_MAP.put("North Am. Rev.","North American Review");
        ABBREVIATION_MAP.put("Norw.","Norwegian");
        ABBREVIATION_MAP.put("Num.","Numbers");
        ABBREVIATION_MAP.put("Numis.","Numismatics");
        ABBREVIATION_MAP.put("O.","Old");
        ABBREVIATION_MAP.put("Ob.","Obadiah");
        ABBREVIATION_MAP.put("Obs.","Obsolete");
        ABBREVIATION_MAP.put("Obsoles.","Obsolescent");
        ABBREVIATION_MAP.put("OCelt.","Old Celtic");
        ABBREVIATION_MAP.put("OD.","Old Dutch");
        ABBREVIATION_MAP.put("ODan.","Old Danish");
        ABBREVIATION_MAP.put("OE.","Old English");
        ABBREVIATION_MAP.put("OF.","Old French");
        ABBREVIATION_MAP.put("OFelm.","Old Flemish");
        ABBREVIATION_MAP.put("OFries.","Old Friesic");
        ABBREVIATION_MAP.put("OGael.","Old Gaelic");
        ABBREVIATION_MAP.put("OGr.","Old Greek");
        ABBREVIATION_MAP.put("OHG.","Old High German");
        ABBREVIATION_MAP.put("OIcel.","Old Icelandic");
        ABBREVIATION_MAP.put("OIr.","Old Irish");
        ABBREVIATION_MAP.put("OIt.","Old Italian");
        ABBREVIATION_MAP.put("OL.","Old Latin");
        ABBREVIATION_MAP.put("OLG.","Old Low Greman");
        ABBREVIATION_MAP.put("ON.","Old Norse");
        ABBREVIATION_MAP.put("OPer.","Old Persian");
        ABBREVIATION_MAP.put("OPg.","Old Portuguese");
        ABBREVIATION_MAP.put("OPol.","Old Polish");
        ABBREVIATION_MAP.put("Opt.","Optics");
        ABBREVIATION_MAP.put("orig.","original, originally");
        ABBREVIATION_MAP.put("Ornith.","Ornithology");
        ABBREVIATION_MAP.put("OS.","Old Saxon");
        ABBREVIATION_MAP.put("OSlav.","Old Slavic");
        ABBREVIATION_MAP.put("OSp.","Old Spanish");
        ABBREVIATION_MAP.put("Oxf. Gloss.","Oxford Glossary of Architecture");
        ABBREVIATION_MAP.put("p.","participle, page");
        ABBREVIATION_MAP.put("p. a.","participial adjective");
        ABBREVIATION_MAP.put("Paint.","Painting");
        ABBREVIATION_MAP.put("Paleon.","Paleontology");
        ABBREVIATION_MAP.put("pass.","passive");
        ABBREVIATION_MAP.put("Pathol.","Pathology");
        ABBREVIATION_MAP.put("P. Cyc.","Penny Cyclopedia");
        ABBREVIATION_MAP.put("Per.","Persian");
        ABBREVIATION_MAP.put("perh.","perhaps");
        ABBREVIATION_MAP.put("pers.","person");
        ABBREVIATION_MAP.put("Persp.","Perspective");
        ABBREVIATION_MAP.put("Pert.","Pertaining");
        ABBREVIATION_MAP.put("Peruv.","Peruvian");
        ABBREVIATION_MAP.put("Pet.","Peter");
        ABBREVIATION_MAP.put("Pg.","Portuguese");
        ABBREVIATION_MAP.put("Pharm.","Pharmacy, Pharmacop<oe/ia");
        ABBREVIATION_MAP.put("Phil.","Phillipians");
        ABBREVIATION_MAP.put("Philem.","Philemon");
        ABBREVIATION_MAP.put("Philol.","Philology");
        ABBREVIATION_MAP.put("Philos.","Philosophy");
        ABBREVIATION_MAP.put("Phon.","Phonetics");
        ABBREVIATION_MAP.put("Photog.","Photography");
        ABBREVIATION_MAP.put("Photom.","Photometry");
        ABBREVIATION_MAP.put("Phr.","Phrase");
        ABBREVIATION_MAP.put("Phren.","Phrenology");
        ABBREVIATION_MAP.put("Phys.","Physics");
        ABBREVIATION_MAP.put("Phys. Sci.","Physical Science");
        ABBREVIATION_MAP.put("Physiol.","Physiology");
        ABBREVIATION_MAP.put("pl.","plural");
        ABBREVIATION_MAP.put("Poet.","Poetry, Poetical");
        ABBREVIATION_MAP.put("Pol.","Polish");
        ABBREVIATION_MAP.put("Pol. Econ.","Political Economy");
        ABBREVIATION_MAP.put("Polit. Econ.","Political Economy");
        ABBREVIATION_MAP.put("Pop. Sci. Monthly","Polular Science Monthly");
        ABBREVIATION_MAP.put("pp.","pages");
        ABBREVIATION_MAP.put("p. p.","participle past");
        ABBREVIATION_MAP.put("P. Plowman","Piers Plowman");
        ABBREVIATION_MAP.put("p. ple.","participle present");
        ABBREVIATION_MAP.put("p. pr.","participle present");
        ABBREVIATION_MAP.put("Pr.","Proven<cced/al");
        ABBREVIATION_MAP.put("Pref.","Preface");
        ABBREVIATION_MAP.put("pref.","prefix");
        ABBREVIATION_MAP.put("prep.","preposition");
        ABBREVIATION_MAP.put("pret.","preterit");
        ABBREVIATION_MAP.put("prin.","principally");
        ABBREVIATION_MAP.put("Print.","Printing");
        ABBREVIATION_MAP.put("priv.","privative");
        ABBREVIATION_MAP.put("prob.","probably");
        ABBREVIATION_MAP.put("pron.","Pronunciation, pronounced, pronoun");
        ABBREVIATION_MAP.put("prop.","properly, proper");
        ABBREVIATION_MAP.put("Pros.","Prosody");
        ABBREVIATION_MAP.put("Prov.","Provincial, Proverbs");
//        ABBREVIATION_MAP.put("Prov.","Proverbs");
        ABBREVIATION_MAP.put("Ps.","Psalms");
        ABBREVIATION_MAP.put("Psa.","Psalms");
        ABBREVIATION_MAP.put("Pyro.-elect.","Pyro-electricity");
        ABBREVIATION_MAP.put("Quart. Rev.","Quarterly Review");
        ABBREVIATION_MAP.put("q. v.","<it>quod vide</it> (which see)");
        ABBREVIATION_MAP.put("R.","Rare");
        ABBREVIATION_MAP.put("R. C.","Roman Catholic");
        ABBREVIATION_MAP.put("R. C. Ch.","Roman Catholic Church");
        ABBREVIATION_MAP.put("Rep. Sec. of War","Report of Secretary of War");
        ABBREVIATION_MAP.put("Rev.","Revelation, Review");
//        ABBREVIATION_MAP.put("Rev.","Review");
        ABBREVIATION_MAP.put("Rev. Ver.","Revised Version (of the Bible)");
        ABBREVIATION_MAP.put("Rhet.","Rhetoric");
        ABBREVIATION_MAP.put("R. of Brunne","Robert of Brunne");
        ABBREVIATION_MAP.put("R. of Gl.","Robert of Gloucester");
        ABBREVIATION_MAP.put("Rom.","Roman, Romans");
        ABBREVIATION_MAP.put("Rom. Cath.","Roman Catholic");
        ABBREVIATION_MAP.put("Rom. of R.","Romaunt of the Rose");
        ABBREVIATION_MAP.put("Rpts.","reports");
        ABBREVIATION_MAP.put("Russ.","Russian");
        ABBREVIATION_MAP.put("Sam.","Samaritan, Samuel");
//        ABBREVIATION_MAP.put("Sam.","Samuel");
        ABBREVIATION_MAP.put("Sat. Rev.","Saturday Review");
        ABBREVIATION_MAP.put("Sax.","Saxon");
        ABBREVIATION_MAP.put("sc.","<it>scilicet</it> (being understood)");
        ABBREVIATION_MAP.put("Scand.","Scandinavian");
        ABBREVIATION_MAP.put("Sci.","Science");
        ABBREVIATION_MAP.put("Sci. Am.","Scientific American");
        ABBREVIATION_MAP.put("Scot.","Scotland, Scottish");
        ABBREVIATION_MAP.put("Script.","Scripture, Scriptural");
        ABBREVIATION_MAP.put("Sculp.","Sculpture");
        ABBREVIATION_MAP.put("Serb","Serbian");
        ABBREVIATION_MAP.put("Serv.","Servian");
        ABBREVIATION_MAP.put("Shak.","Shakespeare");
        ABBREVIATION_MAP.put("sing.","singular");
        ABBREVIATION_MAP.put("Skr.","Sanskrit");
        ABBREVIATION_MAP.put("Slav.","Slavonic");
        ABBREVIATION_MAP.put("Sp.","Spanish");
        ABBREVIATION_MAP.put("Specif.","Specifically");
        ABBREVIATION_MAP.put("Stat.","Statuary");
        ABBREVIATION_MAP.put("subj.","subjunctive");
        ABBREVIATION_MAP.put("superl.","superlative");
        ABBREVIATION_MAP.put("Surg.","Surgery");
        ABBREVIATION_MAP.put("Surv.","Surveying");
        ABBREVIATION_MAP.put("Sw.","Swedish");
        ABBREVIATION_MAP.put("Syd. Soc. Lex.","Sydenham Society Lexicon");
        ABBREVIATION_MAP.put("Syn.","Synonyms");
        ABBREVIATION_MAP.put("Synop.","Synopsis");
        ABBREVIATION_MAP.put("Syr.","Syriac");
        ABBREVIATION_MAP.put("Tart.","Tartaric");
        ABBREVIATION_MAP.put("Teleg.","Telegraphy");
        ABBREVIATION_MAP.put("term.","termination");
        ABBREVIATION_MAP.put("Test.","Testament");
        ABBREVIATION_MAP.put("Theol.","Theology");
        ABBREVIATION_MAP.put("Thes.","Thessalonians");
        ABBREVIATION_MAP.put("Tim.","Timothy");
        ABBREVIATION_MAP.put("Todd & B.","Todd & Bowman");
        ABBREVIATION_MAP.put("Trans.","Translation");
        ABBREVIATION_MAP.put("Treas.","Treasury");
        ABBREVIATION_MAP.put("Trig.","Trigonometry");
        ABBREVIATION_MAP.put("Turk.","Turkish");
        ABBREVIATION_MAP.put("Typog.","Typography");
        ABBREVIATION_MAP.put("Univ.","University");
        ABBREVIATION_MAP.put("Up.","Upper");
        ABBREVIATION_MAP.put("U. S.","United States");
        ABBREVIATION_MAP.put("U. S. Disp.","United States Dispensatory");
        ABBREVIATION_MAP.put("U. S. Pharm.","United States Pharmacop<oe/ia");
        ABBREVIATION_MAP.put("U. S. Int. Rev. Statutes","United States Internal Revenue Statutes");
        ABBREVIATION_MAP.put("usu.","usually");
        ABBREVIATION_MAP.put("v.","verb");
        ABBREVIATION_MAP.put("var.","variety");
        ABBREVIATION_MAP.put("vb. n.","verbal noun");
        ABBREVIATION_MAP.put("Veter.","Veterinary");
        ABBREVIATION_MAP.put("v. i.","verb intransitive");
        ABBREVIATION_MAP.put("Vitr.","Vitruvius");
        ABBREVIATION_MAP.put("v. t.","verb transitive");
        ABBREVIATION_MAP.put("W.","Welsh");
        ABBREVIATION_MAP.put("Wall.","Wallachian");
        ABBREVIATION_MAP.put("Westm. Cat.","Westminster Catechism");
        ABBREVIATION_MAP.put("Westm. Rev.","Westminster Review");
        ABBREVIATION_MAP.put("Zech.","Zechariah");
        ABBREVIATION_MAP.put("Zeph.","Zephaniah");
        ABBREVIATION_MAP.put("Zo\\'94l.","Zo\\'94logy");
    }
}
